version: "3.9"

services:
  level-1:
    build:
      dockerfile: ./common/Dockerfile
      context: .
      args:
        - ASM=level1.S
    ports:
      - "1337:1337"

  level-2:
    build:
      dockerfile: ./common/Dockerfile
      context: .
      args:
        - ASM=level2.S
    ports:
      - "1338:1337"

  level-3:
    build:
      dockerfile: ./common/Dockerfile
      context: .
      args:
        - ASM=level3.S
    ports:
      - "1339:1337"